from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from loguru import logger


@dataclass
class SDDTemplate:
    feature_id: str
    feature_name: str
    commit_hash: str
    commit_message: str
    phase: str
    detected_code_refs: list[str]
    impact_type: str


class SDDGenerator:
    _sdd_dir = Path("docs/sdd")
    _auto_dir = Path("docs/runtime/auto-generated")

    @classmethod
    def generate_sdd(cls, template: SDDTemplate) -> Path:
        cls._sdd_dir.mkdir(parents=True, exist_ok=True)
        cls._auto_dir.mkdir(parents=True, exist_ok=True)

        safe_name = template.feature_id.replace(".", "-").replace("_", "-")
        file_name = f"AUTO-SDD-{safe_name}.md"
        output_path = cls._auto_dir / file_name

        content = cls._build_content(template)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"[sdd_generator] generated: {output_path}")
        return output_path

    @classmethod
    def _build_content(cls, t: SDDTemplate) -> str:
        now = datetime.now(timezone.utc).isoformat()
        frontmatter = f"""---
id: {t.feature_id}
type: generated
phase: {t.phase}
status: inferred
tags: [auto-generated, {t.impact_type}]
links: []
generated_from_commit: {t.commit_hash}
generated_at: {now}
requires_review: true
---

"""

        body = f"""# {t.feature_name} (AUTO-GENERATED)

## Source Commit
- **Hash**: `{t.commit_hash}`
- **Message**: {t.commit_message}
- **Impact Type**: {t.impact_type}

## Detected Code References
"""

        for ref in t.detected_code_refs:
            body += f"- `{ref}`\n"

        body += f"""

## System Layer Impacted
- Event Layer / State Layer / Tool Layer / Provider Layer

## Suggested Tags
#{t.impact_type}

## Status
⚠ **AUTO-GENERATED - REQUIRES MANUAL REVIEW**

## Next Steps
1. Review and validate detected code references
2. Add proper YAML frontmatter with correct links
3. Document responsibilities, emits, used_by
4. Link to related features/SDDs
5. Update status to `active` when complete
"""
        return frontmatter + body

    @classmethod
    def generate_feature_node(cls, feature_id: str, feature_name: str, feature_type: str,
                              phase: str, tags: list[str], links: list[str],
                              description: str, responsibilities: list[str],
                              emits: list[str], used_by: list[str]) -> Path:
        cls._sdd_dir.mkdir(parents=True, exist_ok=True)

        safe_name = feature_id.replace(".", "-").replace("_", "-")
        file_name = f"{safe_name}.md"
        output_path = cls._sdd_dir / file_name

        now = datetime.now(timezone.utc).isoformat()
        frontmatter = f"""---
id: {feature_id}
type: {feature_type}
phase: {phase}
status: active
tags: {tags}
links: {links}
created_at: {now}
updated_at: {now}
---

"""

        body = f"""# {feature_name}

## Description
{description}

## Responsibilities
"""
        for r in responsibilities:
            body += f"- {r}\n"

        body += "\n## Emits\n"
        for e in emits:
            body += f"- {e}\n"

        body += "\n## Used By\n"
        for u in used_by:
            body += f"- {u}\n"

        body += f"\n---\n*Generated by KIRL Auto-Doc Engine at {now}*\n"

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(frontmatter + body)

        logger.info(f"[sdd_generator] generated feature node: {output_path}")
        return output_path

    @classmethod
    def update_feature_node(cls, feature_id: str, updates: dict) -> Optional[Path]:
        safe_name = feature_id.replace(".", "-").replace("_", "-")
        file_name = f"{safe_name}.md"
        output_path = cls._sdd_dir / file_name

        if not output_path.exists():
            return None

        content = output_path.read_text(encoding="utf-8")
        frontmatter_end = content.find("---", 4)
        if frontmatter_end == -1:
            return None

        frontmatter = content[4:frontmatter_end].strip()
        body = content[frontmatter_end + 3:].strip()

        import yaml
        try:
            meta = yaml.safe_load(frontmatter)
        except Exception:
            return None

        meta.update(updates)
        meta["updated_at"] = datetime.now(timezone.utc).isoformat()

        new_frontmatter = yaml.dump(meta, allow_unicode=True, sort_keys=False)
        new_content = f"---\n{new_frontmatter}---\n{body}"

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(new_content)

        logger.info(f"[sdd_generator] updated feature node: {output_path}")
        return output_path