[Interface]
# K.A.O.S VPN Client
PrivateKey = {{CLIENT_PRIVATE_KEY}}
Address = 10.0.0.2/24
DNS = 1.1.1.1

[Peer]
# K.A.O.S VPN Server
PublicKey = {{SERVER_PUBLIC_KEY}}
Endpoint = {{ENDPOINT}}:51820
AllowedIPs = {{ALLOWED_IPS}}
PersistentKeepalive = 25
